
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txxexnclfzvfbqxlibnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eGV4bmNsZnp2ZmJxeGxpYm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTEyMTEsImV4cCI6MjA2MzQyNzIxMX0.Q_QLlLsVqj92V7XotbdIENTIZx7eJXg01NVYKYy2VJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
